version: '3.8'
services:
    nginxproxy:
        image: 'nginx:stable-alpine'
        ports:
            - "3000:80"
            - "5000:80"
        restart: always
        volumes:
            - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'

    nginx:
        depends_on:
            - nginxproxy
        image: nginx:1.18.0
        restart: always

    apache:
        depends_on:
            - nginxproxy
        image: httpd:2.4.46
        restart: always
